// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfsxEjoXHb1MwQ0q2GwxGDQrpHa_OYIfM',
    appId: '1:573020368419:web:be9c1df970acd66d4d4b96',
    messagingSenderId: '573020368419',
    projectId: 'footware-f41be',
    authDomain: 'footware-f41be.firebaseapp.com',
    storageBucket: 'footware-f41be.firebasestorage.app',
    measurementId: 'G-3XX4KMQVBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ70a0Le75uajuGm9Lo5SsNvzZu5gSwM8',
    appId: '1:573020368419:android:bc483ba11063dddf4d4b96',
    messagingSenderId: '573020368419',
    projectId: 'footware-f41be',
    storageBucket: 'footware-f41be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrcg6sULnQYNOum_MF_kT-Z4kFKhZjm0',
    appId: '1:573020368419:ios:ee7fd27f88a512ca4d4b96',
    messagingSenderId: '573020368419',
    projectId: 'footware-f41be',
    storageBucket: 'footware-f41be.firebasestorage.app',
    iosBundleId: 'com.example.fwClient',
  );
}
